config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'

  resources :work do
    collection do
      post :button_start
    end
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    # here will be some code
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <%= render 'partials/home_page/head_home_page.html' %>

  <body>
    <%= render 'partials/home_page/default_body_home_page.html' %>
    <div class="container">
      <div class="starter-template">
        <h1>Super-puper NewCyberBot </h1>
        <p class="lead">
        <form>
          <div class="row">
            <div class="col-md-12">
              <%= form_tag(button_start_work_index_path, method: 'post') do %>
              <% end %>
              <%= form_tag(button_start_work_index_path, method: 'post') do %>
                <%= submit_tag('Start !', class: 'btn btn-primary') %>
              <% end %>
            </div>
          </div>
        </form>
      </div>
    </div>
  </body>
</html>

app/views/home/js.html.erb
<html>
  <head>
  <title>Alertku - Demo</title>
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
  <script type="text/javascript">
      var n = 0;
          function alertku(){
           if(alertku.opt){
            document.getElementById('alertku_span').innerHTML = n;
            n++;
            setTimeout(alertku, 1000);
           }
      };
  </script>
  </head>
  <body>
    <div>
      <input type="button" value="RUN" onclick="alertku.opt = true; alertku();"> 
      <input type="button" value="STOP" onclick="alertku.opt = false;"><br>
      <span id="alertku_span">hum</span>
    </div>
  </body>
</html>